/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ColorValue: typeof import('./src/components/ColorValue.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NIcon: typeof import('naive-ui')['NIcon']
    NP: typeof import('naive-ui')['NP']
    NText: typeof import('naive-ui')['NText']
    NUpload: typeof import('naive-ui')['NUpload']
    NUploadDragger: typeof import('naive-ui')['NUploadDragger']
    Upload: typeof import('./src/components/Upload.vue')['default']
  }
}
